# Generated by Django 2.0.1 on 2018-02-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('0', 'male'), ('1', 'female')], default='1', max_length=1),
        ),
    ]
